### ISSUE TITLE
Support for Dark Theme

### ISSUE THREAD

**Issue by jjardina** [ostreifel/Pull-Request-Search#20]
Dark Theme in Azure DevOps is not honored by the extension.

**Comment by lekeig** [comment]
As a workaround, here's a quick and dirty dark theme I use through the chrome extension Stylus (other similar extensions would work too). To use it, import the following snippet as a new style. Feel free to tweak it to your needs (I styled the form to be more minimalist and rounded the avatars as well).

```css
@-moz-document url-prefix("https://ottostreifel") {
    html {
        background: #201F1E
    }
    .wrapper {
        background: #201F1E
    }
    .input-text-box {
        background: #201F1E;
        border-color: rgb(96, 94, 92);
    }

    /* Hide Header */
    #header {
        display: none;
    }

    /* Text */
    td,
    div,
    input,
    label {
        color: #BBB !important;
        border-color: #444 !important
    }
    #contents-results .cell.line-number {
        background-color: #201F1E
    }
    #message {
        height: 18px;
    }

    /* Link */
    a {
        color: #FFF !important;
    }

    /* Table */
    table {
        background: rgba(50, 50, 50, .6);
    }
    table > tbody > tr:nth-child(even) {
        background-color: rgba(0, 0, 0, .2)
    }
    td.column-pad-right {
    padding: 0 10px;
    }

    /* Dropdown */
    [class*="popup"] {
        background: #201F1E;
    }

    /* Buttons */
    button.cta {
        background-color: #201F1E !important;
        border-color: #444 !important;
        min-width: 9em !important;
        padding: 0 8px;
    }
    button.refresh.cta{
        min-width: 6em !important;
    }
    button.cta:hover {
        background-color: #444 !important;
        border-color: #BBB !important;
    }

    /* Round Avatars */
    img {
        border-radius: 50%;
    }
}
```
